# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cas_server', '0010_auto_20160824_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_attributs', models.TextField(blank=True, default=None, null=True)),
                ('username', models.CharField(max_length=155, unique=True)),
            ],
            options={
                'verbose_name': 'User attributes cache',
                'verbose_name_plural': 'User attributes caches',
            },
        ),
        migrations.AlterModelOptions(
            name='federateduser',
            options={'verbose_name': 'Federated user', 'verbose_name_plural': 'Federated users'},
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
